# Generated by Django 4.1.5 on 2023-02-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_company', models.BooleanField()),
                ('name', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
                ('fio', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service_objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=60)),
                ('position', models.ForeignKey(default='Нет должности', on_delete=django.db.models.deletion.SET_DEFAULT, to='application_processing.positions')),
                ('role', models.ForeignKey(default='Нет роли', on_delete=django.db.models.deletion.SET_DEFAULT, to='application_processing.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('inv_number', models.CharField(max_length=45)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application_processing.equipment_types')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('files', models.FilePathField()),
                ('create_date', models.DateTimeField()),
                ('planned_end_date', models.DateTimeField()),
                ('taken_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_processing.clients')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_processing.equipment')),
                ('priority', models.ForeignKey(default='Нет приоритета', on_delete=django.db.models.deletion.SET_DEFAULT, to='application_processing.priority')),
                ('service_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_processing.service_objects')),
                ('status', models.ForeignKey(default='Создано', on_delete=django.db.models.deletion.SET_DEFAULT, to='application_processing.statuses')),
                ('worker', models.ForeignKey(default='Нет работника', on_delete=django.db.models.deletion.SET_DEFAULT, to='application_processing.workers')),
            ],
        ),
    ]
