# Generated by Django 4.1.5 on 2023-02-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
